name: Build Cross-Compiler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - cross-compiler/**

jobs:
  push:
    name: "swiftly:cross-compiler"
    runs-on: Linux
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./cross-compiler
          file: ./cross-compiler/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/swiftly-solution/swiftly:cross-compiler