name: Build Plugin Cross-Compiler

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 1"
    push:
        branches:
            - master
        paths:
            - plugin-cross-compiler/**

jobs:
    push:
        name: "swiftly:plugin-cross-compiler"
        runs-on: Linux
        permissions:
            contents: read
            packages: write
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
              with:
                  buildkitd-flags: --debug
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@v5
              with:
                  context: ./plugin-cross-compiler
                  file: ./plugin-cross-compiler/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: |
                      ghcr.io/swiftly-solution/swiftly:plugin-cross-compiler
